kind: Service
apiVersion: v1
metadata:
  creationTimestamp: null
  name: sql-database
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: sql-database
    database: sql-database
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  labels:
    run: sql-database
    database: sql-database
  name: sql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sql-database
      database: sql-database
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sql-database
        database: sql-database
    spec:
      containers:
      - image: stephandiegeilesau/my-postgres-image:1
        env:
        - name:  POSTGRES_USER
          value: postgres
        - name:  POSTGRES_PASSWORD
          value: postgres
        imagePullPolicy: IfNotPresent
        name: mysql-database
        ports:
        - containerPort: 5432
        resources: {}
